---
# tasks file for mablanco.tiger

- name: install tiger
  apt:
    name: tiger
    update_cache: yes
    state: present

- name: setup Tiger_Mail_FROM field
  lineinfile:
    dest: "/etc/tiger/tigerrc"
    insertafter: "^# Tiger_Mail_FROM="
    line: "Tiger_Mail_FROM=\"{{ tiger_mail_from }}\""
    state: present

- name: setup Tiger_Mail_RCPT field
  lineinfile:
    dest: "/etc/tiger/tigerrc"
    regexp: "^Tiger_Mail_RCPT="
    line: "Tiger_Mail_RCPT=\"{{ tiger_mail_rcpt }}\""
    state: present
